//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.10.2.0 (NJsonSchema v10.3.4.0 (Newtonsoft.Json v12.0.0.2)) (http://NSwag.org)
// </auto-generated>
//----------------------

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"

namespace ProxyCall.BackendRelay
{
    using System = global::System;
    
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.10.2.0 (NJsonSchema v10.3.4.0 (Newtonsoft.Json v12.0.0.2))")]
    public interface IController
    {
        System.Threading.Tasks.Task<System.Collections.Generic.ICollection<FormInfo>> QueryFormAsync();
    
        System.Threading.Tasks.Task<FormInfo> LoadFormAsync(string formNo);
    
        System.Threading.Tasks.Task<FormInfo> SaveFormAsync(FormInfo body);
    
        System.Threading.Tasks.Task<ErrMsg> LongTimeCalcAsync(int? spend);
    
    }
    
    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.10.2.0 (NJsonSchema v10.3.4.0 (Newtonsoft.Json v12.0.0.2))")]
    public partial class Controller : Microsoft.AspNetCore.Mvc.ControllerBase
    {
        private IController _implementation;
    
        public Controller(IController implementation)
        {
            _implementation = implementation;
        }
    
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("TestForm/QueryForm")]
        public System.Threading.Tasks.Task<System.Collections.Generic.ICollection<FormInfo>> QueryForm()
        {
            return _implementation.QueryFormAsync();
        }
    
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("TestForm/LoadForm")]
        public System.Threading.Tasks.Task<FormInfo> LoadForm([Microsoft.AspNetCore.Mvc.FromQuery] string formNo)
        {
            return _implementation.LoadFormAsync(formNo);
        }
    
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("TestForm/SaveForm")]
        public System.Threading.Tasks.Task<FormInfo> SaveForm([Microsoft.AspNetCore.Mvc.FromBody] FormInfo body)
        {
            return _implementation.SaveFormAsync(body);
        }
    
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("TestForm/LongTimeCalc")]
        public System.Threading.Tasks.Task<ErrMsg> LongTimeCalc([Microsoft.AspNetCore.Mvc.FromQuery] int? spend)
        {
            return _implementation.LongTimeCalcAsync(spend);
        }
    
    }

    

}

#pragma warning restore 1591
#pragma warning restore 1573
#pragma warning restore  472
#pragma warning restore  114
#pragma warning restore  108